### ISSUE TITLE
obuspa crash observed when adding MTP instance from controller

### ISSUE THREAD

**Issue by arunsivasankar** [BroadbandForum/obuspa#73] opened 2023-02-28 14:21 UTC
when initiate a new add object request for mtp instance with including parameter "MQTT.ResponseTopicConfigured" in the request
observing segmentation fault in obuspa

header {
  msg_id: "8-1677145707088:2829835"
  msg_type: ADD
}
body {
  request {
    add {
      create_objs {
        obj_path: "Device.LocalAgent.MTP."
        param_settings {
          param: "Protocol"
          value: "MQTT"
          required: true
        }
        param_settings {
          param: "Enable"
          value: "true"
          required: true
        }
        param_settings {
          param: "MQTT.Reference"
          value: "Device.MQTT.Client.2"
          required: true
        }
        param_settings {
          param: "MQTT.ResponseTopicConfigured"
          value: "/agent-path"
          required: true
        }
      }
    }
  }
}
ADD : processing at time 2023-01-10T17:10:28Z
ERROR: Segmentation Fault
Aborted (core dumped)

logs attached.

Issue not seen when we add instance first and later invoke set on created instance.
step 1 :  Do Add instance from controller 
header {
  msg_id: "8-1677145707088:2829835"
  msg_type: ADD
}
body {
  request {
    add {
      create_objs {
        obj_path: "Device.LocalAgent.MTP."
        param_settings {
          param: "Protocol"
          value: "MQTT"
          required: true
        }
        param_settings {
          param: "Enable"
          value: "true"
          required: true
        }
        param_settings {
          param: "MQTT.Reference"
          value: "Device.MQTT.Client.2"
          required: true
        }
      }
    }
  }
}

step2 : 
invoke set 
header {
  msg_id: "4-1677593126705:3497711"
  msg_type: SET
}
body {
  request {
    set {
      allow_partial: false
      update_objs {
        obj_path: "Device.LocalAgent.MTP.3."
        param_settings {
          param: "MQTT.ResponseTopicConfigured"
          value: "agent-path"
          required: true
        }
      }
    }
  }
}

SET : processing at time 2023-01-10T17:04:27Z

SET_RESP sending at time 2023-01-10T17:04:27Z, to host 135.249.60.21 over MQTT
to_id=self:hdmept:controller
from_id=proto::Axxxxxxxxxx
version: "1.1"
to_id: "self:hdmept:controller"
from_id: "proto::Axxxxxxxx"
payload_security: PLAINTEXT
no_session_context {
}

header {
  msg_id: "4-1677593126705:3497711"
  msg_type: SET_RESP
}
body {
  response {
    set_resp {
      updated_obj_results {
        requested_path: "Device.LocalAgent.MTP.3."
        oper_status {
          oper_success {
            updated_inst_results {
              affected_path: "Device.LocalAgent.MTP.3."
              updated_params {
                key: "MQTT.Reference"
                value: "Device.MQTT.Client.2"
              }
              updated_params {
                key: "MQTT.ResponseTopicConfigured"
                value: "agent-path"
              }
            }
          }
        }
      }
[obuspa_logs.txt](https://github.com/BroadbandForum/obuspa/files/10851166/obuspa_logs.txt)

    }
  }
}

**Comment by arunsivasankar** [comment] 2023-02-28 14:24
obuspa version used : obuspa-7.0.0

**Comment by arunsivasankar** [comment] 2023-03-03 19:34
Is there a way to enable USP_LOG_Callstack,?

#ifdef HAVE_EXECINFO_H
void USP_LOG_Callstack(void)

by default it is disabled  and getting too many compilation issues enabling 
HAVE_EXECINFO_H to get the backtrace

will enable debugging symbols and get the backtrace from gdb and share the backtrace

[obuspa_logs_1.txt](https://github.com/BroadbandForum/obuspa/files/10885531/obuspa_logs_1.txt)

**Comment by holme-r** [comment] 2023-03-06 10:18
HAVE_EXECINFO_H is usually defined for glibc, but not for other C libraries. You don't have to explicitly define it. The callstack functions can only be used if the C library supports it.

**Comment by holme-r** [comment] 2023-03-09 09:55
I am using a proprietary test controller which can send the exact USP protobuf message that you gave in your trace. So this is unlikely to be the reason why I cannot reproduce the issue.
The most likely reason is that you are starting from a different MTP configuration than I am. Another reason might be that you are using a version of OBUSPA that has been modified, and your modifications have broken this case (as in GH#72, which you submitted)

Please could you provide the call stack from the core dump and the initial data model configuration before the Add (obuspa -c show database). Thanks.
BTW You don't need HAVE_EXECINFO_H or USP_LOG_Callstack to get a callstack from the coredump.

**Comment by holme-r** [comment] 2023-04-14 09:59
Closing as there has been no further info forthcoming and I am unable to reproduce the issue. Please re-open including the info requested if this is still a problem.

**Closed by holme-r** 2023-04-14 09:59 UTC
