### ISSUE TITLE
MQTT Subscription Failed

### ISSUE THREAD

**Issue by Luke-Guangzhong** [BroadbandForum/obuspa#23] opened 2021-08-18 06:55 UTC
Hello！

Here is my text which used to build the factory reset database:
![image](https://user-images.githubusercontent.com/78730836/129850602-a5b1a449-0960-404e-bd3a-a56a34d07e71.png)
I used `Device.MQTT.Client.1.Subscription` three times. But when I login in the MQTT Broker, I can only see the topic defined in the `Device.LocalAgent.MTP.1.MQTT.ResponseTopicConfigured`
![image](https://user-images.githubusercontent.com/78730836/129851394-fb5ddda8-9000-4321-bb55-77e41946968c.png)
How to subscribe more topics for the MQTT Client？
Can you help me point out where I have written wrong?

Thanks ！

**Comment by holme-r** [comment] 2021-08-18 12:22
MQTT Subscriptions should work. Are the subscriptions present in the output of 'obuspa -c show database' ?

**Comment by RamonRomeroQro** [comment] 2021-08-18 19:59
Hello!

Same problem here, the subscriptions are defined on the obuspa factory file and on the output for the data base, but no subscribe message is sent to the broker

```
Device.MQTT.Client.1.Subscription.3.Alias => cpe-3
Device.MQTT.Client.1.Subscription.3.Topic => status/usp/newtopic
Device.MQTT.Client.1.Subscription.3.QoS => 1
Device.MQTT.Client.1.Subscription.3.Enable => true
``
## Notes:
- Running using the dockerfile
- My mosquitto acl were also tested to publish and subscribe without problems.
- Also  ```Device.LocalAgent.MTP.1.MQTT.ResponseTopicConfigured  ``` subscribes but not receiving message from broker
-  messages sent to ``` Device.LocalAgent.Controller.1.MTP.1.MQTT.Topic ``` received.


Maybe our configuration files for subscriptions are wrong, could you please share a tested configuration file for one or multiple subcriptions?

Thanks !

**Comment by Luke-Guangzhong** [comment] 2021-08-19 01:41
> MQTT Subscriptions should work. Are the subscriptions present in the output of 'obuspa -c show database' ?

Hi ！
Thank you for reply.
Here is my output of `obuspa -c show database`:
![%6P 2))EYT8A@`3PMK~WGNJ](https://user-images.githubusercontent.com/78730836/129992817-27e90b0c-0c7d-4aa3-aa33-178ed56ec0f5.png)

By the way, I'm using Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64). Do I need to do something else because of my OS?

Thanks ！

**Comment by holme-r** [comment] 2021-08-19 13:34
I can reproduce the issue and am working on a fix.

**Comment by Luke-Guangzhong** [comment] 2021-08-20 00:54
Thank you very much ! 😁

**Comment by RamonRomeroQro** [comment] 2021-08-24 02:57
@Luke-Guangzhong hello, have you already tested, your test your mqtt factory file with the new code?

**Comment by RamonRomeroQro** [comment] 2021-08-24 04:09
@Luke-Guangzhong hello, have you already tested your mqtt factory file with the new code?

**Comment by Luke-Guangzhong** [comment] 2021-08-24 04:47
@RamonRomeroQro Hi! 
I'm sorry, my team leader postponed the task. 
Now I am preparing for the internal exam. 
If I test it, I'll let you know as soon as possible.

**Comment by RamonRomeroQro** [comment] 2021-09-02 19:54
@Luke-Guangzhong already tested with an example similar to the one which you posted, it seems to be working

**Comment by RamonRomeroQro** [comment] 2021-09-02 20:32
@holme-r Thanks for your answers,
2 more doubts, 
- once I have created the subscription, how can I define the topic for the response?
- How can I define a periodic subscription to a specific topic?

Sorry for so many questions, I do not have found a lot of docs

**Comment by Luke-Guangzhong** [comment] 2021-09-03 02:17
@RamonRomeroQro 
I'm sorry, it took a long time to prepare for the internal exam.:sweat_smile:
Thank you very much. 👍

**Comment by holme-r** [comment] 2021-09-03 07:34
@RamonRomeroQro For more info on how USP uses MQTT see:

https://github.com/BroadbandForum/usp/blob/master/specification/mtp/mqtt/index.md
Answers to your questions:
1. The topic for the response is specified by a "reply to" Topic in the
message received by the USP Agent.
2. Sorry, but I don't understand what you mean by a 'periodic
subscription'. It implies you want the subscription to only be active at
certain times (periodically), and I can't understand why you'd want to do
that.

**Comment by RamonRomeroQro** [comment] 2021-09-04 06:13
@holme-r Thank you so much for your work and replies, I have already solve those issues 😁

**Comment by holme-r** [comment] 2021-09-17 14:48
Closing as the fix is committed.

**Closed by holme-r** 2021-09-17 14:48 UTC
