### ISSUE TITLE
obuspa locked/struck during operate execution

### ISSUE THREAD

**Issue by arunsivasankar** [BroadbandForum/obuspa#72] opened 2023-02-15 06:07 UTC
We are observing when operate commands for TR143 Diagnostics are queued, 
during operate response, obuspa gets struck waiting for mutex lock and hangs forever.
Obuspa needs to be killed and restarted to recover the problem
obuspa version : 4.1.0

in issue state, could observe
**futex(0x7fcaaf09ec, FUTEX_WAIT_PRIVATE, 2, NULL** is not acquired and does not return

strace logs
newfstatat(AT_FDCWD, "/configs/usp.db-journal", 0x7fcaaf0158, 0) = -1 ENOENT (No such file or directory)
lseek(10, 24, SEEK_SET)                 = 24
read(10, "\0\0\3\17\0\0\0\3\0\0\0\0\0\0\0\0", 16) = 16
newfstatat(AT_FDCWD, "/configs/usp.db-wal", 0x7fcaaf0158, 0) = -1 ENOENT (No such file or directory)
fstat(10, {st_mode=S_IFREG|0640, st_size=12288, ...}) = 0
fcntl(10, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
fcntl(10, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
fcntl(10, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
fcntl(10, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
newfstatat(AT_FDCWD, "/configs/usp.db-journal", 0x7fcaaf0158, 0) = -1 ENOENT (No such file or directory)
lseek(10, 24, SEEK_SET)                 = 24
read(10, "\0\0\3\17\0\0\0\3\0\0\0\0\0\0\0\0", 16) = 16
newfstatat(AT_FDCWD, "/configs/usp.db-wal", 0x7fcaaf0158, 0) = -1 ENOENT (No such file or directory)
fstat(10, {st_mode=S_IFREG|0640, st_size=12288, ...}) = 0
fcntl(10, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
sendto(27, "\240\t\257\312\177\0\0\0", 8, 0, NULL, 0) = 8
**futex(0x556a2a72bc, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fcaaf091c, FUTEX_WAIT_PRIVATE, 2, NULL) = 0**
sendto(7, "Sending NotifyRequest (Operation"..., 95, 0, NULL, 0) = 95
sendto(18, "W", 1, 0, NULL, 0)          = 1
sendto(7, "Retrying sending notification (r"..., 60, 0, NULL, 0) = 60
fcntl(10, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
fcntl(10, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
fcntl(10, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
newfstatat(AT_FDCWD, "/configs/usp.db-journal", 0x7fcaaf0028, 0) = -1 ENOENT (No such file or directory)
lseek(10, 24, SEEK_SET)                 = 24
read(10, "\0\0\3\17\0\0\0\3\0\0\0\0\0\0\0\0", 16) = 16
newfstatat(AT_FDCWD, "/configs/usp.db-wal", 0x7fcaaf0028, 0) = -1 ENOENT (No such file or directory)
fstat(10, {st_mode=S_IFREG|0640, st_size=12288, ...}) = 0
fcntl(10, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=1073741825, l_len=1}) = 0
newfstatat(AT_FDCWD, "/configs/usp.db", {st_mode=S_IFREG|0640, st_size=12288, ...}, 0) = 0
getpid()                                = 25637
newfstatat(AT_FDCWD, "/configs/usp.db", {st_mode=S_IFREG|0640, st_size=12288, ...}, 0) = 0
openat(AT_FDCWD, "/configs/usp.db-journal", O_RDWR|O_CREAT|O_LARGEFILE|O_NOFOLLOW|O_CLOEXEC, 0640) = 34
fcntl(34, F_SETFD, FD_CLOEXEC)          = 0
fstat(34, {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
geteuid()                               = 0
fchown(34, 0, 0)                        = 0
lseek(34, 0, SEEK_SET)                  = 0
write(34, "\0\0\0\0\0\0\0\0\0\0\0\0\274/w\275\0\0\0\3\0\0\2\0\0\0\20\0\0\0\0\0"..., 512) = 512
lseek(34, 512, SEEK_SET)                = 512
write(34, "\0\0\0\2", 4)                = 4
lseek(34, 516, SEEK_SET)                = 516
write(34, "\r\n\344\0:\n\226\23\17\362\17\336\17\317\17\272\17\255\17\241\17\222\17\205\17v\17a\0172\17!"..., 4096) = 4096
lseek(34, 4612, SEEK_SET)               = 4612
write(34, "\274/y\v", 4)                = 4
lseek(34, 4616, SEEK_SET)               = 4616
write(34, "\0\0\0\3", 4)                = 4
lseek(34, 4620, SEEK_SET)               = 4620
write(34, "\n\0\0\0:\rv\0\17c\17\33\16\237\16\370\16\224\16\33\16~\16\5\17\5\17\340\17\264\17\20"..., 4096) = 4096
lseek(34, 8716, SEEK_SET)               = 8716
write(34, "\274/y\257", 4)              = 4
sendto(27, " \t\257\312\177\0\0\0", 8, 0, NULL, 0) = 8
**futex(0x7fcaaf089c, FUTEX_WAIT_PRIVATE, 2, NULL) = 0**
fcntl(10, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
fcntl(10, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
lseek(34, 8720, SEEK_SET)               = 8720
write(34, "\0\0\0\1", 4)                = 4
lseek(34, 8724, SEEK_SET)               = 8724
write(34, "SQLite format 3\0\20\0\1\1\0@  \0\0\3\17\0\0\0\3"..., 4096) = 4096
lseek(34, 12820, SEEK_SET)              = 12820
write(34, "\274/w\275", 4)              = 4
lseek(34, 13312, SEEK_SET)              = 13312
read(34, "", 8)                         = 0
fdatasync(34)                           = 0
openat(AT_FDCWD, "/configs", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 35
fcntl(35, F_SETFD, FD_CLOEXEC)          = 0
fdatasync(35)                           = 0
close(35)                               = 0
lseek(34, 0, SEEK_SET)                  = 0
write(34, "\331\325\5\371 \241c\327\0\0\0\3", 12) = 12
fdatasync(34)                           = 0
lseek(10, 0, SEEK_SET)                  = 0
write(10, "SQLite format 3\0\20\0\1\1\0@  \0\0\3\20\0\0\0\3"..., 4096) = 4096
lseek(10, 4096, SEEK_SET)               = 4096
write(10, "\r\n\344\0005\n\314\23\17\362\17\336\17\317\17\272\17\255\17\241\17\222\17\205\17v\17a\0172\17!"..., 4096) = 4096
lseek(10, 8192, SEEK_SET)               = 8192
write(10, "\n\0\0\0005\r\255\0\17c\17\33\16\237\16\370\16\224\16\33\16~\16\5\17\5\17\340\17\264\17\20"..., 4096) = 4096
fdatasync(10)                           = 0
close(34)                               = 0
unlinkat(AT_FDCWD, "/configs/usp.db-journal", 0) = 0
fcntl(10, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
fcntl(10, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=2}) = 0
fcntl(10, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
sendto(27, "\0\t\257\312\177\0\0\0", 8, 0, NULL, 0) = 8
**futex(0x556a2a72bc, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fcaaf087c, FUTEX_WAIT_PRIVATE, 2, NULL) = 0**
sendto(27, "\200\10\257\312\177\0\0\0", 8, 0, NULL, 0) = 8
**futex(0x556a2a72bc, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fcaaf07fc, FUTEX_WAIT_PRIVATE, 2, NULL) = 0**
pselect6(31, [11 30], [], [], {tv_sec=7, tv_nsec=0}, {NULL, 8}) = 1 (in [11], left {tv_sec=6, tv_nsec=950535308})
recvfrom(11, "\5\0\0\0\0\0\0\0`\237\377\215U\0\0\0p\0\0\0\0\0\0\0\1\0\0\0\3\0\0\0"..., 104, 0, NULL, NULL) = 104
sendto(7, "version: \"1.1\"\0", 15, 0, NULL, 0) = 15
sendto(7, "to_id: \"os::ABCDED-12345678\"\0", 31, 0, NULL, 0) = 31
sendto(7, "from_id: \"self:hdmept:controller"..., 34, 0, NULL, 0) = 34
sendto(7, "payload_security: PLAINTEXT\0", 28, 0, NULL, 0) = 28
sendto(7, "no_session_context {\0", 21, 0, NULL, 0) = 21
sendto(7, "}\0", 2, 0, NULL, 0)         = 2
sendto(7, "\n\0", 2, 0, NULL, 0)        = 2
sendto(7, "header {\0", 9, 0, NULL, 0)  = 9
sendto(7, "  msg_id: \"OperationComplete-202"..., 54, 0, NULL, 0) = 54
sendto(7, "  msg_type: NOTIFY_RESP\0", 24, 0, NULL, 0) = 24
sendto(7, "}\0", 2, 0, NULL, 0)         = 2
sendto(7, "body {\0", 7, 0, NULL, 0)    = 7
sendto(7, "  response {\0", 13, 0, NULL, 0) = 13
sendto(7, "    notify_resp {\0", 18, 0, NULL, 0) = 18
sendto(7, "      subscription_id: \"2\"\0", 27, 0, NULL, 0) = 27
sendto(7, "    }\0", 6, 0, NULL, 0)     = 6
sendto(7, "  }\0", 4, 0, NULL, 0)       = 4
sendto(7, "}\0", 2, 0, NULL, 0)         = 2
sendto(7, "\n\0", 2, 0, NULL, 0)        = 2
sendto(7, "NOTIFY_RESP : processing at time"..., 54, 0, NULL, 0) = 54
sendto(7, "SUBS_RETRY_Remove: Removing Noti"..., 126, 0, NULL, 0) = 126
pselect6(31, [11 30], [], [], {tv_sec=13, tv_nsec=0}, {NULL, 8}) = 0 (Timeout)
pselect6(31, [11 30], [], [], {tv_sec=12, tv_nsec=0}, {NULL, 8}) = 0 (Timeout)
sendto(7, "Sending NotifyRequest (Event for"..., 67, 0, NULL, 0) = 67
sendto(18, "W", 1, 0, NULL, 0)          = 1
sendto(7, "Retrying sending notification (r"..., 60, 0, NULL, 0) = 60
pselect6(31, [11 30], [], [], {tv_sec=3, tv_nsec=0}, {NULL, 8}) = 1 (in [11], left {tv_sec=2, tv_nsec=740579077})
recvfrom(11, "\5\0\0\0\0\0\0\0\300\237\377\215U\0\0\0d\0\0\0\0\0\0\0\1\0\0\0\3\0\0\0"..., 104, 0, NULL, NULL) = 104
sendto(7, "version: \"1.1\"\0", 15, 0, NULL, 0) = 15
sendto(7, "to_id: \"os::ABCDED-12345678\"\0", 31, 0, NULL, 0) = 31
sendto(7, "from_id: \"self:hdmept:controller"..., 34, 0, NULL, 0) = 34
sendto(7, "payload_security: PLAINTEXT\0", 28, 0, NULL, 0) = 28
sendto(7, "no_session_context {\0", 21, 0, NULL, 0) = 21
sendto(7, "}\0", 2, 0, NULL, 0)         = 2
sendto(7, "\n\0", 2, 0, NULL, 0)        = 2
sendto(7, "header {\0", 9, 0, NULL, 0)  = 9
sendto(7, "  msg_id: \"Event-2023-02-13T06:5"..., 42, 0, NULL, 0) = 42
sendto(7, "  msg_type: NOTIFY_RESP\0", 24, 0, NULL, 0) = 24
sendto(7, "}\0", 2, 0, NULL, 0)         = 2
sendto(7, "body {\0", 7, 0, NULL, 0)    = 7
sendto(7, "  response {\0", 13, 0, NULL, 0) = 13
sendto(7, "    notify_resp {\0", 18, 0, NULL, 0) = 18
sendto(7, "      subscription_id: \"3\"\0", 27, 0, NULL, 0) = 27
sendto(7, "    }\0", 6, 0, NULL, 0)     = 6
sendto(7, "  }\0", 4, 0, NULL, 0)       = 4
sendto(7, "}\0", 2, 0, NULL, 0)         = 2
sendto(7, "\n\0", 2, 0, NULL, 0)        = 2
sendto(7, "NOTIFY_RESP : processing at time"..., 54, 0, NULL, 0) = 54
sendto(7, "SUBS_RETRY_Remove: Removing Noti"..., 114, 0, NULL, 0) = 114
pselect6(31, [11 30], [], [], {tv_sec=3, tv_nsec=0}, {NULL, 8}) = 0 (Timeout)
pselect6(31, [11 30], [], [], {tv_sec=15, tv_nsec=0}, {NULL, 8}) = 0 (Timeout)
pselect6(31, [11 30], [], [], {tv_sec=15, tv_nsec=0}, {NULL, 8}) = 0 (Timeout)
pselect6(31, [11 30], [], [], {tv_sec=15, tv_nsec=0}, {NULL, 8}) = 1 (in [11], left {tv_sec=8, tv_nsec=645338154})
recvfrom(11, "\5\0\0\0\0\0\0\0@\213\377\215U\0\0\0\206\1\0\0\0\0\0\0\1\0\0\0\3\0\0\0"..., 104, 0, NULL, NULL) = 104
sendto(7, "version: \"1.1\"\0", 15, 0, NULL, 0) = 15
sendto(7, "to_id: \"os::ABCDED-12345678\"\0", 31, 0, NULL, 0) = 31
sendto(7, "from_id: \"self:hdmept:controller"..., 34, 0, NULL, 0) = 34
sendto(7, "payload_security: PLAINTEXT\0", 28, 0, NULL, 0) = 28
sendto(7, "no_session_context {\0", 21, 0, NULL, 0) = 21
sendto(7, "}\0", 2, 0, NULL, 0)         = 2
sendto(7, "\n\0", 2, 0, NULL, 0)        = 2
sendto(7, "header {\0", 9, 0, NULL, 0)  = 9
sendto(7, "  msg_id: \"2600416\"\0", 20, 0, NULL, 0) = 20
sendto(7, "  msg_type: OPERATE\0", 20, 0, NULL, 0) = 20
sendto(7, "}\0", 2, 0, NULL, 0)         = 2
sendto(7, "body {\0", 7, 0, NULL, 0)    = 7
sendto(7, "  request {\0", 12, 0, NULL, 0) = 12
sendto(7, "    operate {\0", 14, 0, NULL, 0) = 14
sendto(7, "      command: \"Device.IP.Diagno"..., 59, 0, NULL, 0) = 59
sendto(7, "      command_key: \"OfZWQtG\"\0", 29, 0, NULL, 0) = 29
sendto(7, "      send_resp: true\0", 22, 0, NULL, 0) = 22
sendto(7, "      input_args {\0", 19, 0, NULL, 0) = 19
sendto(7, "        key: \"EnablePerConnectio"..., 42, 0, NULL, 0) = 42
sendto(7, "        value: \"true\"\0", 22, 0, NULL, 0) = 22
sendto(7, "      }\0", 8, 0, NULL, 0)   = 8
sendto(7, "      input_args {\0", 19, 0, NULL, 0) = 19
sendto(7, "        key: \"UploadURL\"\0", 25, 0, NULL, 0) = 25
sendto(7, "        value: \"http://10.121.11."..., 56, 0, NULL, 0) = 56
sendto(7, "      }\0", 8, 0, NULL, 0)   = 8
sendto(7, "      input_args {\0", 19, 0, NULL, 0) = 19
sendto(7, "        key: \"TimeBasedTestDurat"..., 37, 0, NULL, 0) = 37
sendto(7, "        value: \"10\"\0", 20, 0, NULL, 0) = 20
sendto(7, "      }\0", 8, 0, NULL, 0)   = 8
sendto(7, "      input_args {\0", 19, 0, NULL, 0) = 19
sendto(7, "        key: \"TimeBasedTestMeasu"..., 48, 0, NULL, 0) = 48
sendto(7, "        value: \"5\"\0", 19, 0, NULL, 0) = 19
sendto(7, "      }\0", 8, 0, NULL, 0)   = 8
sendto(7, "      input_args {\0", 19, 0, NULL, 0) = 19
sendto(7, "        key: \"TimeBasedTestMeasu"..., 46, 0, NULL, 0) = 46
sendto(7, "        value: \"3\"\0", 19, 0, NULL, 0) = 19
sendto(7, "      }\0", 8, 0, NULL, 0)   = 8
sendto(7, "      input_args {\0", 19, 0, NULL, 0) = 19
sendto(7, "        key: \"NumberOfConnection"..., 35, 0, NULL, 0) = 35
sendto(7, "        value: \"5\"\0", 19, 0, NULL, 0) = 19
sendto(7, "      }\0", 8, 0, NULL, 0)   = 8
sendto(7, "      input_args {\0", 19, 0, NULL, 0) = 19
sendto(7, "        key: \"Interface\"\0", 25, 0, NULL, 0) = 25
sendto(7, "        value: \"Device.IP.Interf"..., 39, 0, NULL, 0) = 39
sendto(7, "      }\0", 8, 0, NULL, 0)   = 8
sendto(7, "    }\0", 6, 0, NULL, 0)     = 6
sendto(7, "  }\0", 4, 0, NULL, 0)       = 4
sendto(7, "}\0", 2, 0, NULL, 0)         = 2
sendto(7, "\n\0", 2, 0, NULL, 0)        = 2
sendto(7, "OPERATE : processing at time 202"..., 50, 0, NULL, 0) = 50
sendto(27, "\20\v\257\312\177\0\0\0", 8, 0, NULL, 0) = 8
**futex(0x556a2a72bc, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fcaaf0a8c, FUTEX_WAIT_PRIVATE, 2, NULL) = 0**
fcntl(10, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
fcntl(10, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
fcntl(10, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
newfstatat(AT_FDCWD, "/configs/usp.db-journal", 0x7fcaaeee38, 0) = -1 ENOENT (No such file or directory)
lseek(10, 24, SEEK_SET)                 = 24
read(10, "\0\0\3\20\0\0\0\3\0\0\0\0\0\0\0\0", 16) = 16
newfstatat(AT_FDCWD, "/configs/usp.db-wal", 0x7fcaaeee38, 0) = -1 ENOENT (No such file or directory)
fstat(10, {st_mode=S_IFREG|0640, st_size=12288, ...}) = 0
fcntl(10, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=1073741825, l_len=1}) = 0
newfstatat(AT_FDCWD, "/configs/usp.db", {st_mode=S_IFREG|0640, st_size=12288, ...}, 0) = 0
getpid()                                = 25637
newfstatat(AT_FDCWD, "/configs/usp.db", {st_mode=S_IFREG|0640, st_size=12288, ...}, 0) = 0
openat(AT_FDCWD, "/configs/usp.db-journal", O_RDWR|O_CREAT|O_LARGEFILE|O_NOFOLLOW|O_CLOEXEC, 0640) = 34
fcntl(34, F_SETFD, FD_CLOEXEC)          = 0
fstat(34, {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
geteuid()                               = 0
fchown(34, 0, 0)                        = 0
lseek(34, 0, SEEK_SET)                  = 0
write(34, "\0\0\0\0\0\0\0\0\0\0\0\0\273Y!%\0\0\0\3\0\0\2\0\0\0\20\0\0\0\0\0"..., 512) = 512
lseek(34, 512, SEEK_SET)                = 512
write(34, "\0\0\0\3", 4)                = 4
lseek(34, 516, SEEK_SET)                = 516
write(34, "\n\0\0\0005\r\255\0\17c\17\33\16\237\16\370\16\224\16\33\16~\16\5\17\5\17\340\17\264\17\20"..., 4096) = 4096
lseek(34, 4612, SEEK_SET)               = 4612
write(34, "\273Y#\30", 4)               = 4
lseek(34, 4616, SEEK_SET)               = 4616
write(34, "\0\0\0\2", 4)                = 4
lseek(34, 4620, SEEK_SET)               = 4620
write(34, "\r\n\344\0005\n\314\23\17\362\17\336\17\317\17\272\17\255\17\241\17\222\17\205\17v\17a\0172\17!"..., 4096) = 4096
lseek(34, 8716, SEEK_SET)               = 8716
write(34, "\273Y\"s", 4)                = 4
sendto(27, "P\n\257\312\177\0\0\0", 8, 0, NULL, 0) = 8
**futex(0x556a2a72bc, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fcaaf09cc, FUTEX_WAIT_PRIVATE, 2, NULL) = 0**
sendto(27, "\220\n\257\312\177\0\0\0", 8, 0, NULL, 0) = 8
**futex(0x556a2a72bc, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fcaaf0a0c, FUTEX_WAIT_PRIVATE, 2, NULL) = 0**
fcntl(10, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
fcntl(10, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
lseek(34, 8720, SEEK_SET)               = 8720
write(34, "\0\0\0\1", 4)                = 4
lseek(34, 8724, SEEK_SET)               = 8724
write(34, "SQLite format 3\0\20\0\1\1\0@  \0\0\3\20\0\0\0\3"..., 4096) = 4096
lseek(34, 12820, SEEK_SET)              = 12820
write(34, "\273Y!%", 4)                 = 4
lseek(34, 13312, SEEK_SET)              = 13312
read(34, "", 8)                         = 0
fdatasync(34)                           = 0
openat(AT_FDCWD, "/configs", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 35
fcntl(35, F_SETFD, FD_CLOEXEC)          = 0
fdatasync(35)                           = 0
close(35)                               = 0
lseek(34, 0, SEEK_SET)                  = 0
write(34, "\331\325\5\371 \241c\327\0\0\0\3", 12) = 12
fdatasync(34)                           = 0
lseek(10, 0, SEEK_SET)                  = 0
write(10, "SQLite format 3\0\20\0\1\1\0@  \0\0\3\21\0\0\0\3"..., 4096) = 4096
lseek(10, 4096, SEEK_SET)               = 4096
write(10, "\r\n\344\0:\n\230\23\17\362\17\336\17\317\17\272\17\255\17\241\17\222\17\205\17v\17a\0172\17!"..., 4096) = 4096
lseek(10, 8192, SEEK_SET)               = 8192
write(10, "\n\0\0\0:\rv\0\17c\17\33\16\237\16\370\16\224\16\33\16~\16\5\17\5\17\340\17\264\17\20"..., 4096) = 4096
fdatasync(10)                           = 0
close(34)                               = 0
unlinkat(AT_FDCWD, "/configs/usp.db-journal", 0) = 0
fcntl(10, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
fcntl(10, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=2}) = 0
fcntl(10, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
sendto(27, "p\n\257\312\177\0\0\0", 8, 0, NULL, 0) = 8
**futex(0x7fcaaf09ec, FUTEX_WAIT_PRIVATE, 2, NULL**  **<struck and locked here>**

database : 
/ # obuspa -c show database
Running command on database /configs/usp.db
Device.MQTT.Client.1.ProtocolVersion => 5.0
Device.MQTT.Client.1.Alias => cpemqtt-1
Device.MQTT.Client.1.Enable => true
Device.MQTT.Client.1.ClientID => 12345678
Device.MQTT.Client.1.KeepAliveTime => 60
Device.MQTT.Client.1.ConnectRetryTime => 5
Device.MQTT.Client.1.ConnectRetryIntervalMultiplier => 2000
Device.MQTT.Client.1.ConnectRetryMaxInterval => 60
Device.LocalAgent.Controller.1.Enable => true
Device.LocalAgent.Controller.1.Alias => cpe-cont-1
Device.LocalAgent.Controller.1.PeriodicNotifTime => 0001-01-01T00:00:00Z
Device.LocalAgent.Controller.1.MTP.1.Enable => true
Device.LocalAgent.Controller.1.MTP.1.Alias => cpe-cont-mtp-1
Device.LocalAgent.Controller.1.MTP.1.Protocol => MQTT
Device.LocalAgent.Controller.1.MTP.1.MQTT.Reference => Device.MQTT.Client.1
Device.LocalAgent.Controller.1.MTP.1.MQTT.Topic => hdm/usp/endpoint/controller/notifications
Device.LocalAgent.MTP.1.Enable => true
Device.LocalAgent.MTP.1.Alias => cpe-mtp-1
Device.LocalAgent.MTP.1.MQTT.ResponseTopicConfigured => hdm/usp/endpoint/agent/os::***************
Device.LocalAgent.MTP.1.MQTT.Reference => Device.MQTT.Client.1
Device.LocalAgent.Controller.1.BootParameter.1.Enable => true
Device.LocalAgent.Controller.1.BootParameter.1.ParameterName => Device.LocalAgent.EndpointID
Device.LocalAgent.Controller.1.EndpointID => self:hdmept:controller
Device.LocalAgent.MTP.1.Protocol => MQTT
Device.MQTT.Client.1.TransportProtocol => TCP/IP
Device.MQTT.Client.1.BrokerAddress => *********
Device.MQTT.Client.1.BrokerPort => 1883
Device.MQTT.Client.1.Username => ********
Device.MQTT.Client.1.Password => **********
Device.LocalAgent.Subscription.1.Recipient => Device.LocalAgent.Controller.1
Device.LocalAgent.Subscription.1.CreationDate => 2023-02-10T02:32:32Z
Device.LocalAgent.Subscription.1.Alias => hdm-subscription-opc
Device.LocalAgent.Subscription.1.Enable => true
Device.LocalAgent.Subscription.1.ID => 2
Device.LocalAgent.Subscription.1.NotifType => OperationComplete
Device.LocalAgent.Subscription.1.ReferenceList => Device.
Device.LocalAgent.Subscription.1.Persistent => true
Device.LocalAgent.Subscription.1.TimeToLive => 0
Device.LocalAgent.Subscription.1.NotifRetry => true
Device.LocalAgent.Subscription.1.NotifExpiration => 3600
Device.LocalAgent.Subscription.2.Recipient => Device.LocalAgent.Controller.1
Device.LocalAgent.Subscription.2.CreationDate => 2023-02-10T02:32:32Z
Device.LocalAgent.Subscription.2.Alias => hdm-subscription-et
Device.LocalAgent.Subscription.2.Enable => true
Device.LocalAgent.Subscription.2.ID => 3
Device.LocalAgent.Subscription.2.NotifType => Event
Device.LocalAgent.Subscription.2.ReferenceList => Device.
Device.LocalAgent.Subscription.2.Persistent => true
Device.LocalAgent.Subscription.2.TimeToLive => 0
Device.LocalAgent.Subscription.2.NotifRetry => true
Device.LocalAgent.Subscription.2.NotifExpiration => 3600
Internal.Reboot.LastSoftwareVersion => *********
Device.LocalAgent.Controller.1.PeriodicNotifInterval => 300

**Comment by holme-r** [comment] 2023-02-15 08:47
Specifically which operate command(s) is this ?
Also It would be useful to give the call stacks of all threads when the problem has occurred.
Finally, OBUSPA 4.1.0 is quite old now. Does the problem still occur on the latest release (7.1) ?

**Comment by holme-r** [comment] 2023-02-16 17:12
It sounds like there maybe a problem with the implementation of the Upload and Download IP diagnostics, if they are causing a lockup. But OBUSPA doesn't include any code to implement these diagnostics, so this doesn't sound like an OBUSPA issue, but more a problem with the code that has been added to implement those IP Diagnostics.

If you have written code to run these diagnostics in another thread, you must not call any functions which take the data model mutex. Your operate thread should only be calling USP_SIGNAL_OperationStatus(), USP_SIGNAL_OperationComplete() and the USP_ARG_XXX() set of functions.

**Comment by arunsivasankar** [comment] 2023-02-24 07:50
sure richard holme, we will revisit and check the vendor code for handling of data model mutex, if any
you can put this issue on hold for now, I shall get back to you with additional information when ready.

**Comment by johnblackford** [comment] 2023-03-10 15:30
Closing this issue as we believe the the problem is in the vendor extension code - please re-open if that turns out to not be the case.

**Closed by johnblackford** 2023-03-10 15:30 UTC
