### ISSUE TITLE
docker creation using existing Dockerfile does not work

### ISSUE THREAD

**Issue by openuspio** [BroadbandForum/obuspa#95] opened 2023-10-30 14:14 UTC
=> ERROR [build-env 2/2] RUN apt-get update && apt-get -y install         libssl-dev         libcurl4-openssl-dev        libsqlite3-dev         libz-dev     1.9s
------                                                                                                                                                             
 > [build-env 2/2] RUN apt-get update && apt-get -y install         libssl-dev         libcurl4-openssl-dev        libsqlite3-dev         libz-dev         autoconf         automake         libtool         libmosquitto-dev         libwebsockets-dev         pkg-config         make     && apt-get clean:                         
0.573 Ign:1 http://ports.ubuntu.com/ubuntu-ports kinetic InRelease                                                                                                 
0.727 Ign:2 http://ports.ubuntu.com/ubuntu-ports kinetic-updates InRelease                                                                                         
0.895 Ign:3 http://ports.ubuntu.com/ubuntu-ports kinetic-backports InRelease                                                                                       
1.051 Ign:4 http://ports.ubuntu.com/ubuntu-ports kinetic-security InRelease
1.206 Err:5 http://ports.ubuntu.com/ubuntu-ports kinetic Release
1.206   404  Not Found [IP: 185.125.190.36 80]
1.367 Err:6 http://ports.ubuntu.com/ubuntu-ports kinetic-updates Release
1.367   404  Not Found [IP: 185.125.190.36 80]
1.524 Err:7 http://ports.ubuntu.com/ubuntu-ports kinetic-backports Release
1.524   404  Not Found [IP: 185.125.190.36 80]
1.686 Err:8 http://ports.ubuntu.com/ubuntu-ports kinetic-security Release
1.686   404  Not Found [IP: 185.125.190.36 80]
1.695 Reading package lists...
1.709 E: The repository 'http://ports.ubuntu.com/ubuntu-ports kinetic Release' does not have a Release file.
1.709 E: The repository 'http://ports.ubuntu.com/ubuntu-ports kinetic-updates Release' does not have a Release file.
1.709 E: The repository 'http://ports.ubuntu.com/ubuntu-ports kinetic-backports Release' does not have a Release file.
1.710 E: The repository 'http://ports.ubuntu.com/ubuntu-ports kinetic-security Release' does not have a Release file.
------
Dockerfile:21
--------------------
  20 |     # Install dependencies
  21 | >>> RUN apt-get update && apt-get -y install \
  22 | >>>         libssl-dev \
  23 | >>>         libcurl4-openssl-dev\
  24 | >>>         libsqlite3-dev \
  25 | >>>         libz-dev \
  26 | >>>         autoconf \
  27 | >>>         automake \
  28 | >>>         libtool \
  29 | >>>         libmosquitto-dev \
  30 | >>>         libwebsockets-dev \
  31 | >>>         pkg-config \
  32 | >>>         make \
  33 | >>>     && apt-get clean
  34 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update && apt-get -y install         libssl-dev         libcurl4-openssl-dev        libsqlite3-dev         libz-dev         autoconf         automake         libtool         libmosquitto-dev         libwebsockets-dev         pkg-config         make     && apt-get clean" did not complete successfully: exit code: 100

**Comment by anderewrey** [comment] 2023-10-30 14:36
@openuspio   There's indeed a problem and I'm able to reproduce it. However, I fear I can't help on that since the problem is on Ubuntu side and not us.  If I replace the Ubuntu version of that `FROM ubuntu:kinetic AS build-env` line for `jammy`instead of `kinetic`, the ubuntu repos are found correctly.

As a workaround, you may try to use a different Ubuntu version instead of kinetic (22.04): jammy (20.04) or lunar (23.04).

**Comment by openuspio** [comment] 2023-10-30 18:02
Hi @anderewrey , added a fix and raised a pull request. Please feel free to contact me if you have any question regarding the fix.
Thanks

**Comment by holme-r** [comment] 2024-08-19 16:34
Closing as Dockerfile has been fixed in v8.0.8.

**Closed by holme-r** 2024-08-19 16:34 UTC
