### ISSUE TITLE
Question about stomp heartbeat

### ISSUE THREAD

**Issue by shinedd** [BroadbandForum/obuspa#106] opened 2024-04-22 11:18 UTC
When i set Device.STOMP.Connection.1.OutgoingHeartbeat to non-0, i will get a error like this

![image](https://github.com/BroadbandForum/obuspa/assets/106661626/30d1aa6c-bbb2-42f0-ad23-42dba3a7a285)

Then i change value to 0, obuspa work normally

![image](https://github.com/BroadbandForum/obuspa/assets/106661626/2fc2a4e7-d500-446f-b1ef-395b1625e60b)

**Comment by holme-r** [comment] 2024-04-23 08:23
Please see https://stomp.github.io/stomp-specification-1.2.html#Heart-beating
In the first log, the negotiated heartbeat time for the agent is 3 seconds, and the log shows that OBUSPA is sending heartbeats every 3 seconds. However the STOMP Broker is disconnecting.
I think the problem is that the STOMP Broker is too keen to close the connection if the heart beat is not received EXACTLY within 3000ms of the last. The STOMP spec states "the receiver SHOULD be tolerant and take into account an error margin".  This is needed to allow for timing differences and network delays. OBUSPA allows a 10 second error margin on reception of STOMP broker heartbeats before closing the connection.
Perhaps the very small heart beat times that you're using is being interpreted by the STOMP broker as a correspondingly small error margin. Have you tried a larger value for OutgoingHeartbeat ? Normally this would be about 30 seconds (not 3 seconds).
Which STOMP broker is this issue seen with ?

**Closed** 2024-07-05 14:26 UTC
Labels: question
